<a href="https://colab.research.google.com/github/vivek-231/homework/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix

from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

In [6]:
from os import name
filename=r'/content/pima-indians-diabetes.data.csv'
names=[ 'preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=pd.read_csv(filename,names=names)
array=dataframe.values
x=array[:,0:7]
y=array[:,7]

In [7]:
x
y

array([50., 31., 32., 21., 33., 30., 26., 29., 53., 54., 30., 34., 57.,
       59., 51., 32., 31., 31., 33., 32., 27., 50., 41., 29., 51., 41.,
       43., 22., 57., 38., 60., 28., 22., 28., 45., 33., 35., 46., 27.,
       56., 26., 37., 48., 54., 40., 25., 29., 22., 31., 24., 22., 26.,
       30., 58., 42., 21., 41., 31., 44., 22., 21., 39., 36., 24., 42.,
       32., 38., 54., 25., 27., 28., 26., 42., 23., 22., 22., 41., 27.,
       26., 24., 22., 22., 36., 22., 37., 27., 45., 26., 43., 24., 21.,
       34., 42., 60., 21., 40., 24., 22., 23., 31., 33., 22., 21., 24.,
       27., 21., 27., 37., 25., 24., 24., 46., 23., 25., 39., 61., 38.,
       25., 22., 21., 25., 24., 23., 69., 23., 26., 30., 23., 40., 62.,
       33., 33., 30., 39., 26., 31., 21., 22., 29., 28., 55., 38., 22.,
       42., 23., 21., 41., 34., 65., 22., 24., 37., 42., 23., 43., 36.,
       21., 23., 22., 47., 36., 45., 27., 21., 32., 41., 22., 34., 29.,
       29., 36., 29., 25., 23., 33., 36., 42., 26., 47., 37., 32

In [8]:
x_train ,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [9]:
x_test

array([[  3.   , 169.   ,  74.   , ..., 125.   ,  29.9  ,   0.268],
       [  4.   , 141.   ,  74.   , ...,   0.   ,  27.6  ,   0.244],
       [  4.   ,  76.   ,  62.   , ...,   0.   ,  34.   ,   0.391],
       ...,
       [  2.   ,  92.   ,  76.   , ...,   0.   ,  24.2  ,   1.698],
       [  6.   , 119.   ,  50.   , ..., 176.   ,  27.1  ,   1.318],
       [  0.   , 180.   ,  90.   , ...,  90.   ,  36.5  ,   0.314]])

In [10]:
x_train

array([[  3.   , 141.   ,   0.   , ...,   0.   ,  30.   ,   0.761],
       [  4.   , 136.   ,  70.   , ...,   0.   ,  31.2  ,   1.182],
       [  3.   , 173.   ,  78.   , ..., 185.   ,  33.8  ,   0.97 ],
       ...,
       [  5.   , 110.   ,  68.   , ...,   0.   ,  26.   ,   0.292],
       [  8.   , 107.   ,  80.   , ...,   0.   ,  24.6  ,   0.856],
       [  0.   , 131.   ,  88.   , ...,   0.   ,  31.6  ,   0.743]])

In [11]:
clf=SVC()
param_grid=[{
    'C':[0.1,1,10],
    'gamma':[0.01,0.1,1],
    'kernel':['rbf']
}]
gsv=GridSearchCV(clf,param_grid,cv=10)
gsv.fit(x_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(


GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [0.1, 1, 10], 'gamma': [0.01, 0.1, 1],
                          'kernel': ['rbf']}])

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

svc=SVC()
param_grid=[{
    'C':[0.1,1,10],
    'gamma':[0.01,0.1,1],
    'kernel':['rbf']
}]
grid_search=GridSearchCV(svc,param_grid=param_grid,cv=10)
grid_search.fit(x_train, y_train)
print("Best Performance:",grid_search.best_score_)
print("Best Cross-validation score:",grid_search.best_params_)

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(


Best Performance: 0.08635642517186673
Best Cross-validation score: {'C': 0.1, 'gamma': 0.01, 'kernel': 'rbf'}
